### ISSUE TITLE
Does this plugin support RFID Scan in flutter (android)

### ISSUE THREAD

**Issue by singhanamika** [sanketwarule/zebra_scanner_plugin#6]
I'm using RFD8500 device and want to scan the rfid. I have followed all the instruction of read me and use https://www.zebra.com/us/en/support-downloads/software/developer-tools/rfid-sdk-for-android.html 2.0.2.82 sdk version. I'm trying to incorporate the method like this in flutter 
Future<void> initAndConnectScanner() async {
    try {
      await ZebraScannerPlugin.initScanner;
      print("Scanner initialized successfully.");
      await ZebraScannerPlugin.connect();
      print("connected");
    } catch (e) {
      print("Error initializing or connecting: $e");
    }
  }

I'm getting this: Scanner initialized successfully.
E/MethodChannel#zebra_scanner_plugin(24638): Failed to handle method call
E/MethodChannel#zebra_scanner_plugin(24638): java.lang.NullPointerException: Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkSetDelegate(com.zebra.scannercontrol.IDcsSdkApiDelegate)' on a null object reference
E/MethodChannel#zebra_scanner_plugin(24638):    at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.initialize(ZebraScannerEngine.java:52)
E/MethodChannel#zebra_scanner_plugin(24638):    at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.<init>(ZebraScannerEngine.java:31)
E/MethodChannel#zebra_scanner_plugin(24638):    at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.getInstance(ZebraScannerEngine.java:37)
E/MethodChannel#zebra_scanner_plugin(24638):    at com.androsys.zebra_scanner_plugin.ZebraScannerPlugin.onMethodCall(ZebraScannerPlugin.java:71)
E/MethodChannel#zebra_scanner_plugin(24638):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#zebra_scanner_plugin(24638):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#zebra_scanner_plugin(24638):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#zebra_scanner_plugin(24638):    at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#zebra_scanner_plugin(24638):    at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#zebra_scanner_plugin(24638):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#zebra_scanner_plugin(24638):    at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#zebra_scanner_plugin(24638):    at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#zebra_scanner_plugin(24638):    at android.app.ActivityThread.main(ActivityThread.java:7898)
E/MethodChannel#zebra_scanner_plugin(24638):    at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#zebra_scanner_plugin(24638):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#zebra_scanner_plugin(24638):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (24638): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkSetDelegate(com.zebra.scannercontrol.IDcsSdkApiDelegate)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkSetDelegate(com.zebra.scannercontrol.IDcsSdkApiDelegate)' on a null object reference
E/flutter (24638):      at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.initialize(ZebraScannerEngine.java:52)
E/flutter (24638):      at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.<init>(ZebraScannerEngine.java:31)
E/flutter (24638):      at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.getInstance(ZebraScannerEngine.java:37)
E/flutter (24638):      at com.androsys.zebra_scanner_plugin.ZebraScannerPlugin.onMethodCall(ZebraScannerPlugin.java:71)
E/flutter (24638):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (24638):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (24638):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (24638):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (24638):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (24638):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (24638):      at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (24638):      at android.os.Looper.loop(Looper.java:288)
E/flutter (24638):      at android.app.ActivityThread.main(ActivityThread.java:7898)
E/flutter (24638):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24638):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (24638):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (24638): )
E/flutter (24638): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (24638): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter (24638): <asynchronous suspension>
E/flutter (24638): 
I/flutter (24638): connected
W/ty.asset_mobile(24638): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/ty.asset_mobile(24638): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/CompatibilityChangeReporter(24638): Compat change id reported: 210923482; UID 10000; state: ENABLED
D/AndroidRuntime(24638): Shutting down VM
E/AndroidRuntime(24638): FATAL EXCEPTION: main
E/AndroidRuntime(24638): Process: com.apptricity.asset_mobile, PID: 24638
E/AndroidRuntime(24638): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.apptricity.asset_mobile/com.androsys.zebra_scanner_plugin.ConnectionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkEnableAvailableScannersDetection(boolean)' on a null object reference
E/AndroidRuntime(24638):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
E/AndroidRuntime(24638):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(24638):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(24638):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(24638):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(24638):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(24638):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24638):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(24638):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(24638):        at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(24638):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24638):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(24638):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(24638): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkEnableAvailableScannersDetection(boolean)' on a null object reference
E/AndroidRuntime(24638):        at com.androsys.zebra_scanner_plugin.ConnectionActivity.initializeDcsSdk(ConnectionActivity.java:154)
E/AndroidRuntime(24638):        at com.androsys.zebra_scanner_plugin.ConnectionActivity.initialize(ConnectionActivity.java:149)
E/AndroidRuntime(24638):        at com.androsys.zebra_scanner_plugin.ConnectionActivity.checkPermissionAndInitialize(ConnectionActivity.java:144)
E/AndroidRuntime(24638):        at com.androsys.zebra_scanner_plugin.ConnectionActivity.onCreate(ConnectionActivity.java:68)
E/AndroidRuntime(24638):        at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(24638):        at android.app.Activity.performCreate(Activity.java:8269)
E/AndroidRuntime(24638):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime(24638):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/AndroidRuntime(24638):        ... 12 more
I/Process (24638): Sending signal. PID: 24638 SIG: 9
Lost connection to device.

**Comment by sanketwarule** [comment]
Hello  everyone,

I want to let you know that I currently do not have access to a Zebra scanner device. However, I've developed a Zebra scanner integration and made it available publicly here.

I encourage you to explore the project, contribute, and help enhance its functionality. Your contributions will not only help improve the project but also benefit other developers in the community.

Thank you for your support and collaboration!

Best regards,
Sanket Warule
