### ISSUE TITLE
Attempt to invoke virtual method

### ISSUE THREAD

**Issue by Simphiwe-Jiyane** [sanketwarule/zebra_scanner_plugin#7]
Hi,

I am trying to use the plugin however I am encountering an issue when trying to initialise the scanner. Please may you assist

E/MethodChannel#zebra_scanner_plugin(13722): java.lang.NullPointerException: Attempt to invoke virtual method 'com.zebra.scannercontrol.DCSSDKDefs$DCSSDK_RESULT com.zebra.scannercontrol.SDKHandler.dcssdkSetDelegate(com.zebra.scannercontrol.IDcsSdkApiDelegate)' on a null object reference
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.initialize(ZebraScannerEngine.java:52)
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.<init>(ZebraScannerEngine.java:31)
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.androsys.zebra_scanner_plugin.ZebraScannerEngine.getInstance(ZebraScannerEngine.java:37)
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.androsys.zebra_scanner_plugin.ZebraScannerPlugin.onMethodCall(ZebraScannerPlugin.java:71)
E/MethodChannel#zebra_scanner_plugin(13722): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#zebra_scanner_plugin(13722): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#zebra_scanner_plugin(13722): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#zebra_scanner_plugin(13722): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#zebra_scanner_plugin(13722): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#zebra_scanner_plugin(13722): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#zebra_scanner_plugin(13722): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#zebra_scanner_plugin(13722): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/MethodChannel#zebra_scanner_plugin(13722): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#zebra_scanner_plugin(13722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by sanketwarule** [comment]
Hello  everyone,

I want to let you know that I currently do not have access to a Zebra scanner device. However, I've developed a Zebra scanner integration and made it available publicly here.

I encourage you to explore the project, contribute, and help enhance its functionality. Your contributions will not only help improve the project but also benefit other developers in the community.

Thank you for your support and collaboration!

Best regards,
Sanket Warule
